
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package co.poc.bmind.webservices.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730040-redhat-00001
 * 2020-07-27T15:58:59.495-05:00
 * Generated source version: 3.2.7.fuse-730040-redhat-00001
 *
 */

@javax.jws.WebService(
                      serviceName = "$service.ServiceName",
                      targetNamespace = "$service.Namespace",
                      endpointInterface = "co.poc.bmind.webservices.soap.AplicacionPort")

public class AplicacionPortImpl implements AplicacionPort {

    private static final Logger LOG = Logger.getLogger(AplicacionPortImpl.class.getName());

    /* (non-Javadoc)
     * @see co.poc.bmind.webservices.soap.AplicacionPort#updateAplicacion(co.poc.bmind.webservices.schemas.Aplicacion request)*
     */
    public co.poc.bmind.webservices.schemas.Aplicacion updateAplicacion(co.poc.bmind.webservices.schemas.Aplicacion request) throws FaultMessage   {
        LOG.info("Executing operation updateAplicacion");
        System.out.println(request);
        try {
            co.poc.bmind.webservices.schemas.Aplicacion _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("faultMessage...");
    }

    /* (non-Javadoc)
     * @see co.poc.bmind.webservices.soap.AplicacionPort#deleteAplicacion(java.lang.String request)*
     */
    public co.poc.bmind.webservices.schemas.Correcto deleteAplicacion(java.lang.String request) throws FaultMessage   {
        LOG.info("Executing operation deleteAplicacion");
        System.out.println(request);
        try {
            co.poc.bmind.webservices.schemas.Correcto _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("faultMessage...");
    }

    /* (non-Javadoc)
     * @see co.poc.bmind.webservices.soap.AplicacionPort#getAplicaciones(java.lang.String request)*
     */
    public co.poc.bmind.webservices.schemas.Aplicaciones getAplicaciones(java.lang.String request) throws FaultMessage   {
        LOG.info("Executing operation getAplicaciones");
        System.out.println(request);
        try {
            co.poc.bmind.webservices.schemas.Aplicaciones _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("faultMessage...");
    }

    /* (non-Javadoc)
     * @see co.poc.bmind.webservices.soap.AplicacionPort#addAplicacion(co.poc.bmind.webservices.schemas.Aplicacion request)*
     */
    public co.poc.bmind.webservices.schemas.Aplicacion addAplicacion(co.poc.bmind.webservices.schemas.Aplicacion request) throws FaultMessage   {
        LOG.info("Executing operation addAplicacion");
        System.out.println(request);
        try {
            co.poc.bmind.webservices.schemas.Aplicacion _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultMessage("faultMessage...");
    }

}
