package co.poc.bmind.webservices.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-730040-redhat-00001
 * 2020-07-27T15:58:59.520-05:00
 * Generated source version: 3.2.7.fuse-730040-redhat-00001
 *
 */
@WebService(targetNamespace = "http://www.bmind.poc.co/webservices/soap", name = "AplicacionPort")
@XmlSeeAlso({co.poc.bmind.webservices.schemas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AplicacionPort {

    @WebMethod(action = "updateAplicacion", operationName = "updateAplicacion")
    @WebResult(name = "aplicacion", targetNamespace = "http://www.bmind.poc.co/webservices/schemas", partName = "response")
    public co.poc.bmind.webservices.schemas.Aplicacion updateAplicacion(
        @WebParam(partName = "request", name = "aplicacion", targetNamespace = "http://www.bmind.poc.co/webservices/schemas")
        co.poc.bmind.webservices.schemas.Aplicacion request
    ) throws FaultMessage;

    @WebMethod(action = "deleteAplicacion", operationName = "deleteAplicacion")
    @WebResult(name = "correcto", targetNamespace = "http://www.bmind.poc.co/webservices/schemas", partName = "response")
    public co.poc.bmind.webservices.schemas.Correcto deleteAplicacion(
        @WebParam(partName = "request", name = "id", targetNamespace = "http://www.bmind.poc.co/webservices/schemas")
        java.lang.String request
    ) throws FaultMessage;

    @WebMethod(action = "getAplicaciones", operationName = "getAplicaciones")
    @WebResult(name = "aplicaciones", targetNamespace = "http://www.bmind.poc.co/webservices/schemas", partName = "response")
    public co.poc.bmind.webservices.schemas.Aplicaciones getAplicaciones(
        @WebParam(partName = "request", name = "id", targetNamespace = "http://www.bmind.poc.co/webservices/schemas")
        java.lang.String request
    ) throws FaultMessage;

    @WebMethod(action = "addAplicacion", operationName = "addAplicacion")
    @WebResult(name = "aplicacion", targetNamespace = "http://www.bmind.poc.co/webservices/schemas", partName = "response")
    public co.poc.bmind.webservices.schemas.Aplicacion addAplicacion(
        @WebParam(partName = "request", name = "aplicacion", targetNamespace = "http://www.bmind.poc.co/webservices/schemas")
        co.poc.bmind.webservices.schemas.Aplicacion request
    ) throws FaultMessage;
}
