
package co.poc.bmind.webservices.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7.fuse-730040-redhat-00001
 * 2020-07-27T15:58:59.460-05:00
 * Generated source version: 3.2.7.fuse-730040-redhat-00001
 */

@WebFault(name = "error", targetNamespace = "http://www.bmind.poc.co/webservices/schemas")
public class FaultMessage extends Exception {

    private co.poc.bmind.webservices.schemas.Error error;

    public FaultMessage() {
        super();
    }

    public FaultMessage(String message) {
        super(message);
    }

    public FaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, co.poc.bmind.webservices.schemas.Error error) {
        super(message);
        this.error = error;
    }

    public FaultMessage(String message, co.poc.bmind.webservices.schemas.Error error, java.lang.Throwable cause) {
        super(message, cause);
        this.error = error;
    }

    public co.poc.bmind.webservices.schemas.Error getFaultInfo() {
        return this.error;
    }
}
